import '../models/models.dart';

final LessonModule earthquakeModule = const LessonModule(
  id: 'm3',
  title: 'Earthquake Drill',
  titleBn: 'ভূমিকম্প মহড়া',
  category: HazardCategory.earthquake,
  summary: 'Practice Drop, Cover and Hold On during an earthquake.',
  summaryBn: 'ভূমিকম্পের সময় নত হও, ঢেকে রাখো এবং ধরে থাকো অনুশীলন করুন।',
  steps: [
    'Know the earthquake drill "Drop, Cover, and Hold On" by heart.',
    'Identify safe spots in each room, such as under a sturdy table or desk.',
    'Stay away from windows, mirrors, and heavy furniture that could fall over.',
    'Heavy furniture and shelves should be secured to the wall to prevent tipping.',
    'Keep a flashlight and emergency kit in an easy-to-reach place at home.',
    'If indoors when the shaking starts, drop to the ground immediately.',
    'Cover your head and neck with your arms, or get under sturdy furniture.',
    'Hold on to your shelter firmly until the shaking has completely stopped.',
    'Never run outside during the shaking — falling debris makes it dangerous.',
    'If outdoors, move to an open area away from buildings, trees, and power lines.',
    'If riding in a car, pull over safely and stay inside until the shaking stops.',
    'Elevators must never be used during or immediately after an earthquake.',
    'If in bed when it happens, stay there and cover your head with a pillow.',
    'Stay away from glass windows, outside doors, and walls during the shaking.',
    'After the shaking stops, check yourself and others nearby for injuries.',
    'Be prepared for aftershocks, which can happen minutes or even days later.',
    'If a gas smell is noticed, the gas supply should be turned off if it is safe.',
    'Matches or candles must never be lit if a gas leak is suspected.',
    'Small fires should be checked for and put out immediately if it is safe.',
    'Damaged buildings should be exited carefully and calmly, using stairs, not elevators.',
    'Sturdy shoes should be worn to protect feet from broken glass and debris.',
    'A battery-powered radio should be used to listen for official emergency information.',
    'Only emergency phone calls should be made, to keep phone lines open for rescuers.',
    'Every family should have a meeting point planned outside in case of separation.',
    'Earthquake drills should be practiced at home and school at least twice a year.',
  ],
  stepsBn: [
    '"নত হও, ঢেকে রাখো এবং ধরে থাকো" ভূমিকম্প মহড়াটি মুখস্থ রাখা উচিত।',
    'প্রতিটি ঘরে নিরাপদ জায়গা যেমন মজবুত টেবিল বা ডেস্কের নিচে চিহ্নিত করে রাখতে হবে।',
    'পড়ে যেতে পারে এমন জানালা, আয়না ও ভারী আসবাবপত্র থেকে দূরে থাকা উচিত।',
    'ভারী আসবাবপত্র ও তাক দেয়ালের সাথে বেঁধে রাখা উচিত যাতে তা উল্টে না পড়ে।',
    'বাসায় হাতের নাগালে একটি ফ্ল্যাশলাইট ও জরুরি সরঞ্জাম রাখা উচিত।',
    'ঘরের ভেতরে কম্পন শুরু হলে সাথে সাথে নিচে নত হয়ে বসতে হবে।',
    'হাত দিয়ে মাথা ও ঘাড় ঢেকে রাখতে হবে অথবা মজবুত আসবাবের নিচে যেতে হবে।',
    'কম্পন সম্পূর্ণ থামা পর্যন্ত আশ্রয়স্থল শক্ত করে ধরে রাখতে হবে।',
    'কম্পনের সময় কখনো বাইরে দৌড়ানো উচিত নয় — পড়ে থাকা ধ্বংসাবশেষ বিপজ্জনক।',
    'বাইরে থাকলে ভবন, গাছ ও বিদ্যুতের তার থেকে দূরে খোলা জায়গায় যেতে হবে।',
    'গাড়িতে থাকলে নিরাপদে গাড়ি থামিয়ে কম্পন থামা পর্যন্ত ভেতরে অপেক্ষা করতে হবে।',
    'ভূমিকম্পের সময় বা তার পরপরই লিফট কখনো ব্যবহার করা যাবে না।',
    'বিছানায় থাকলে সেখানেই থেকে বালিশ দিয়ে মাথা ঢেকে রাখতে হবে।',
    'কম্পনের সময় কাচের জানালা, বাইরের দরজা ও দেয়াল থেকে দূরে থাকতে হবে।',
    'কম্পন থামার পর নিজের ও আশেপাশের মানুষের আঘাত পরীক্ষা করতে হবে।',
    'পরাঘাত (আফটারশক) মিনিট বা এমনকি দিন পরেও হতে পারে, তার জন্য প্রস্তুত থাকতে হবে।',
    'গ্যাসের গন্ধ পেলে নিরাপদ হলে গ্যাসের সরবরাহ বন্ধ করে দিতে হবে।',
    'গ্যাস লিক হওয়ার আশঙ্কা থাকলে দিয়াশলাই বা মোমবাতি কখনো জ্বালানো উচিত নয়।',
    'নিরাপদ হলে ছোট আগুন খুঁজে সাথে সাথে নিভিয়ে ফেলা উচিত।',
    'ক্ষতিগ্রস্ত ভবন থেকে শান্তভাবে সিঁড়ি ব্যবহার করে বের হতে হবে, লিফট নয়।',
    'কাচ ও ধ্বংসাবশেষ থেকে পা বাঁচাতে মজবুত জুতা পরা উচিত।',
    'সরকারি জরুরি তথ্যের জন্য ব্যাটারি চালিত রেডিও শোনা উচিত।',
    'উদ্ধারকারীদের জন্য ফোন লাইন খোলা রাখতে শুধু জরুরি কল করা উচিত।',
    'বিচ্ছিন্ন হয়ে গেলে দেখা করার জন্য প্রতিটি পরিবারের একটি বাইরের মিলনস্থল ঠিক থাকা উচিত।',
    'বছরে অন্তত দুইবার বাসায় ও স্কুলে ভূমিকম্প মহড়া অনুশীলন করা উচিত।',
  ],
  stepIcons: [
    '🏋️', '🛡️', '🪟', '🗄️', '🔦', '⬇️', '🙆', '🤲',
    '🏃', '🌳', '🚗', '🛗', '🛏️', '🚪', '🩹', '🌀',
    '⛽', '🕯️', '🔥', '🏢', '👟', '📻', '📵', '👨‍👩‍👧', '🔁',
  ],
);

final Quiz earthquakeQuiz = const Quiz(
  id: 'q3',
  moduleId: 'm3',
  title: 'Earthquake Safety Quiz',
  difficulty: 'Medium',
  questions: [
    QuizQuestion(
      question: 'What should you do during an earthquake indoors?',
      questionBn: 'ঘরের ভেতরে ভূমিকম্পের সময় তোমার কী করা উচিত?',
      options: [
        'Run outside immediately',
        'Drop, Cover and Hold On',
        'Stand near a window',
        'Use the elevator',
      ],
      optionsBn: [
        'সাথে সাথে বাইরে দৌড়াও',
        'নত হও, ঢেকে রাখো এবং ধরে থাকো',
        'জানালার কাছে দাঁড়াও',
        'লিফট ব্যবহার করো',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Where is a safe place to shelter during shaking?',
      questionBn: 'কম্পনের সময় আশ্রয় নেওয়ার নিরাপদ জায়গা কোনটি?',
      options: ['Under a sturdy table', 'Near a glass window', 'On the balcony', 'In the elevator'],
      optionsBn: ['মজবুত টেবিলের নিচে', 'কাচের জানালার কাছে', 'বারান্দায়', 'লিফটে'],
      correctIndex: 0,
    ),
    QuizQuestion(
      question: 'Should you use the elevator during an earthquake?',
      questionBn: 'ভূমিকম্পের সময় লিফট ব্যবহার করা উচিত কি?',
      options: ['Yes, it is fastest', 'No, never', 'Only going down', 'Only if empty'],
      optionsBn: ['হ্যাঁ, এটা দ্রুততম', 'না, কখনোই না', 'শুধু নিচে নামতে', 'শুধু খালি থাকলে'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'If you are outdoors during an earthquake, where should you go?',
      questionBn: 'ভূমিকম্পের সময় বাইরে থাকলে তোমার কোথায় যাওয়া উচিত?',
      options: [
        'Next to a building',
        'An open area away from buildings and wires',
        'Under a tree',
        'Near power lines',
      ],
      optionsBn: [
        'ভবনের পাশে',
        'ভবন ও তারের থেকে দূরে খোলা জায়গায়',
        'গাছের নিচে',
        'বিদ্যুতের তারের কাছে',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What should you do after the shaking stops?',
      questionBn: 'কম্পন থামার পর তোমার কী করা উচিত?',
      options: [
        'Check yourself and others for injuries',
        'Go back to sleep',
        'Light a candle',
        'Use the elevator to check floors',
      ],
      optionsBn: [
        'নিজের ও অন্যদের আঘাত পরীক্ষা করা',
        'আবার ঘুমাতে যাওয়া',
        'মোমবাতি জ্বালানো',
        'লিফট দিয়ে তলা পরীক্ষা করা',
      ],
      correctIndex: 0,
    ),
    QuizQuestion(
      question: 'What are aftershocks?',
      questionBn: 'পরাঘাত (আফটারশক) কী?',
      options: [
        'Smaller quakes that can follow the main one',
        'A type of storm',
        'A safety drill',
        'A rescue vehicle',
      ],
      optionsBn: [
        'মূল ভূমিকম্পের পরে হওয়া ছোট কম্পন',
        'এক ধরনের ঝড়',
        'একটি নিরাপত্তা মহড়া',
        'একটি উদ্ধার যান',
      ],
      correctIndex: 0,
    ),
    QuizQuestion(
      question: 'If you smell gas after an earthquake, what should you do?',
      questionBn: 'ভূমিকম্পের পর গ্যাসের গন্ধ পেলে তোমার কী করা উচিত?',
      options: [
        'Light a candle to check',
        'Turn off the gas supply if safe',
        'Ignore it',
        'Use a lighter',
      ],
      optionsBn: [
        'পরীক্ষা করতে মোমবাতি জ্বালানো',
        'নিরাপদ হলে গ্যাস সরবরাহ বন্ধ করা',
        'উপেক্ষা করা',
        'লাইটার ব্যবহার করা',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Why should you only make emergency calls after an earthquake?',
      questionBn: 'ভূমিকম্পের পর শুধু জরুরি কল করা উচিত কেন?',
      options: [
        'To keep phone lines open for rescuers',
        'Phones don\'t work otherwise',
        'It saves battery',
        'There is no reason',
      ],
      optionsBn: [
        'উদ্ধারকারীদের জন্য ফোন লাইন খোলা রাখতে',
        'অন্যথায় ফোন কাজ করে না',
        'এতে ব্যাটারি বাঁচে',
        'কোনো কারণ নেই',
      ],
      correctIndex: 0,
    ),
    QuizQuestion(
      question: 'What should you wear when leaving a damaged building?',
      questionBn: 'ক্ষতিগ্রস্ত ভবন থেকে বের হওয়ার সময় তোমার কী পরা উচিত?',
      options: ['Bare feet', 'Sturdy shoes', 'Sandals only', 'Socks only'],
      optionsBn: ['খালি পা', 'মজবুত জুতা', 'শুধু স্যান্ডেল', 'শুধু মোজা'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'How often should earthquake drills be practiced?',
      questionBn: 'কত ঘন ঘন ভূমিকম্প মহড়া অনুশীলন করা উচিত?',
      options: ['Never', 'Once every few years', 'At least twice a year', 'Only after a quake'],
      optionsBn: ['কখনোই না', 'কয়েক বছরে একবার', 'বছরে অন্তত দুইবার', 'শুধু ভূমিকম্পের পরে'],
      correctIndex: 2,
    ),
  ],
);
