import '../models/models.dart';

final LessonModule earthquakeModule = const LessonModule(
  id: 'm3',
  title: 'Earthquake Safety Basics',
  titleBn: 'ভূমিকম্প নিরাপত্তার মূলনীতি',
  category: HazardCategory.earthquake,
  summary: 'Learn what to do before, during, and after an earthquake.',
  summaryBn: 'ভূমিকম্পের আগে, সময়ে এবং পরে কী করতে হবে তা শিখুন।',
  steps: [
    'During shaking, Drop, Cover, and Hold On immediately to protect yourself.',
    'Stay indoors if you are already inside and move away from windows and glass.',
    'Take shelter under a sturdy table or desk if one is nearby.',
    'Protect your head and neck with your arms or a backpack.',
    'Do not run outside while the ground is shaking.',
    'Do not use elevators during or immediately after an earthquake.',
    'If you are outside, move to an open area away from buildings, trees, and power lines.',
    'If you are in a vehicle, stop safely and stay inside until the shaking stops.',
    'Stay away from shelves, hanging objects, mirrors, and heavy furniture.',
    'After the shaking stops, check yourself and others for injuries.',
    'Use a flashlight instead of candles if the power goes out.',
    'Expect aftershocks and be ready to Drop, Cover, and Hold On again.',
    'Leave damaged buildings carefully when it is safe to do so.',
    'Listen to parents, teachers, and emergency workers for instructions.',
    'Turn off gas only if an adult says it is safe and you know how.',
    'Check for broken glass, cracks, and fallen objects before walking around.',
    'Text or call family members only when it is safe and necessary.',
    'Know your family meeting place outside the home.',
    'Keep emergency supplies like water, medicine, and a torch ready at home.',
    'Practice earthquake drills with your family so everyone remembers the steps.',
    'Learn the local emergency number and use it when help is needed.',
    'If you smell gas, move away immediately and tell an adult.',
    'Help younger children stay calm and follow the safety steps.',
    'Never re-enter a damaged building until adults say it is safe.',
    'Keep calm and follow the safety plan until the situation is under control.',
  ],
  stepsBn: [
    'ঝাঁকুনি শুরু হলে সাথে সাথে নত হও, ঢেকে রাখো এবং ধরে থাকো।',
    'ভিতরে থাকলে জানালা ও কাচ থেকে দূরে সরে যাও।',
    'কাছাকাছি মজবুত টেবিল বা ডেস্ক থাকলে তার নিচে আশ্রয় নাও।',
    'হাত বা ব্যাগ দিয়ে মাথা ও গলা ঢেকে রাখো।',
    'মাটি কাঁপতে থাকা অবস্থায় বাইরে দৌড়ো না।',
    'ভূমিকম্পের সময় বা ঠিক পরে লিফট ব্যবহার কোরো না।',
    'বাইরে থাকলে ভবন, গাছ ও বিদ্যুতের তার থেকে দূরে খোলা জায়গায় যাও।',
    'গাড়ির ভেতরে থাকলে নিরাপদে থামো এবং ঝাঁকুনি থামা পর্যন্ত ভেতরে থাকো।',
    'শেলফ, ঝুলন্ত জিনিস, আয়না ও ভারী আসবাব থেকে দূরে থাকো।',
    'ঝাঁকুনি থামার পরে নিজের ও অন্যদের আঘাত আছে কি না দেখো।',
    'বিদ্যুৎ চলে গেলে মোমবাতির বদলে টর্চ ব্যবহার করো।',
    'পরের ঝাঁকুনি বা আফটারশক আবার হতে পারে, তাই প্রস্তুত থাকো।',
    'নিরাপদ হলে ক্ষতিগ্রস্ত ভবন থেকে সাবধানে বের হও।',
    'বাবা-মা, শিক্ষক ও উদ্ধারকর্মীদের নির্দেশনা মনোযোগ দিয়ে শোনো।',
    'বড়রা নিরাপদ বললে এবং তুমি জানলে গ্যাস বন্ধ করো।',
    'হাঁটার আগে ভাঙা কাচ, ফাটল ও পড়ে যাওয়া জিনিস আছে কি না দেখো।',
    'নিরাপদ এবং প্রয়োজন হলে তবেই পরিবারের সাথে যোগাযোগ করো।',
    'বাড়ির বাইরে পরিবারের মিলনস্থল আগে থেকেই জেনে রাখো।',
    'ঘরে পানি, ওষুধ ও টর্চসহ জরুরি সামগ্রী প্রস্তুত রাখো।',
    'পরিবারের সাথে ভূমিকম্পের মহড়া অনুশীলন করো যাতে সবাই মনে রাখে।',
    'স্থানীয় জরুরি নম্বর জেনে রাখো এবং প্রয়োজনে ব্যবহার করো।',
    'গ্যাসের গন্ধ পেলে সাথে সাথে দূরে সরে যাও এবং বড়দের বলো।',
    'ছোটদের শান্ত থাকতে সাহায্য করো এবং নিরাপত্তার নিয়ম মানতে বলো।',
    'বড়রা নিরাপদ না বলা পর্যন্ত ক্ষতিগ্রস্ত ভবনে আবার যেও না।',
    'শান্ত থাকো এবং পরিস্থিতি ঠিক না হওয়া পর্যন্ত নিরাপত্তা পরিকল্পনা মেনে চলো।',
  ],
  stepIcons: [
    '👇', '🪟', '🪑', '🛡️', '🏃', '🛗', '🌳', '🚗',
    '📚', '🩹', '🔦', '⚠️', '🚪', '👂', '⛽', '🪟',
    '📱', '🏠', '🎒', '👨‍👩‍👧‍👦', '☎️', '👃', '🤝',
    '🏚️', '🧘',
  ],
);

const Quiz earthquakeMindGameQuiz = Quiz(
  id: 'q3',
  moduleId: 'm3',
  title: 'Earthquake Safety Mind Game',
  difficulty: 'Medium',
  questions: [
    QuizQuestion(
      question: 'What should you do during an earthquake indoors?',
      questionBn: 'ঘরের ভেতরে ভূমিকম্পের সময় তোমার কী করা উচিত?',
      options: [
        'Run outside immediately',
        'Drop, Cover and Hold On',
        'Stand near a window',
        'Use the elevator',
      ],
      optionsBn: [
        'সাথে সাথে বাইরে দৌড়াও',
        'নত হও, ঢেকে রাখো এবং ধরে থাকো',
        'জানালার কাছে দাঁড়াও',
        'লিফট ব্যবহার করো',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What is the safest place to stay during shaking?',
      questionBn: 'ঝাঁকুনির সময় সবচেয়ে নিরাপদে কোথায় থাকা উচিত?',
      options: [
        'Near a window',
        'Under a sturdy table',
        'On the stairs',
        'In the elevator',
      ],
      optionsBn: [
        'জানালার কাছে',
        'মজবুত টেবিলের নিচে',
        'সিঁড়ির ওপর',
        'লিফটে',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'After an earthquake, what should you avoid?',
      questionBn: 'ভূমিকম্পের পরে তোমার কী এড়িয়ে চলা উচিত?',
      options: [
        'Checking for cracks',
        'Going near damaged walls',
        'Listening to adults',
        'Moving to a safe open area',
      ],
      optionsBn: [
        'ফাটল পরীক্ষা করা',
        'ক্ষতিগ্রস্ত দেয়ালের কাছে যাওয়া',
        'বড়দের কথা শোনা',
        'নিরাপদ খোলা জায়গায় যাওয়া',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Which action best protects your head during an earthquake?',
      questionBn: 'ভূমিকম্পের সময় মাথা বাঁচাতে কোনটি সবচেয়ে ভালো?',
      options: [
        'Cover it with your arms and hold on',
        'Look out the window',
        'Run as fast as possible',
        'Stand on a chair',
      ],
      optionsBn: [
        'হাত দিয়ে ঢেকে ধরে থাকা',
        'জানালার বাইরে দেখা',
        'যত দ্রুত সম্ভব দৌড়ানো',
        'চেয়ারের ওপর দাঁড়ানো',
      ],
      correctIndex: 0,
    ),
  ],
);

final Quiz earthquakeQuiz = earthquakeMindGameQuiz;
