import '../models/models.dart';

final LessonModule floodModule = const LessonModule(
  id: 'm2',
  title: 'Flood Preparedness',
  titleBn: 'বন্যা প্রস্তুতি',
  category: HazardCategory.flood,
  summary: 'Understand how to stay safe before and during a flood.',
  summaryBn: 'বন্যার আগে ও সময়ে নিরাপদ থাকার উপায় জানুন।',
  steps: [
    'Know your area\'s flood risk and the nearest evacuation routes in advance.',
    'Keep a battery-powered radio at home to receive weather updates during storms.',
    'Store an emergency kit with clean water, food, a flashlight, and first aid supplies.',
    'Keep important documents like ID cards and certificates in a waterproof bag.',
    'Learn to recognize official flood warning signs and alerts from local authorities.',
    'Move valuable items and electrical appliances to higher shelves before a flood arrives.',
    'Turn off electricity and gas at the main switch if flooding is expected.',
    'Never walk through moving flood water, even if it looks shallow and calm.',
    'Just six inches of fast-moving water can knock a person off their feet.',
    'Never drive through a flooded road — turn around, don\'t drown.',
    'A single foot of moving water is enough to sweep a car away.',
    'Move to higher ground immediately as soon as a flood warning is issued.',
    'Avoid contact with flood water, as it may be contaminated with sewage or chemicals.',
    'Stay far away from downed power lines that may be touching flood water.',
    'Keep away from riverbanks, canals, and drains during periods of heavy rain.',
    'If trapped in a building, move to the highest level, but avoid a closed attic.',
    'Signal for help from a window or rooftop rather than hiding in a closed attic.',
    'Always listen to a trusted adult and local officials for evacuation instructions.',
    'Boil or purify drinking water after a flood, since it might be contaminated.',
    'Do not use electrical appliances that have been flooded until an adult checks them.',
    'Watch out for snakes and insects that may be displaced by rising flood water.',
    'After a flood, stay away from buildings that look cracked or structurally unsafe.',
    'Keep a family emergency contact list and a meeting point outside the flood zone.',
    'The national emergency helpline number should be memorized by every child.',
    'Practice a family flood evacuation plan regularly so everyone knows what to do.',
  ],
  stepsBn: [
    'নিজের এলাকার বন্যার ঝুঁকি এবং নিকটতম নিরাপদ যাওয়ার পথ আগে থেকে জেনে রাখা উচিত।',
    'ঝড়ের সময় আবহাওয়ার খবর পেতে বাসায় একটি ব্যাটারি চালিত রেডিও রাখা উচিত।',
    'পরিষ্কার পানি, খাবার, ফ্ল্যাশলাইট ও প্রাথমিক চিকিৎসা সামগ্রী দিয়ে একটি জরুরি ব্যাগ প্রস্তুত রাখতে হবে।',
    'পরিচয়পত্র ও সনদের মতো গুরুত্বপূর্ণ কাগজপত্র জলরোধী ব্যাগে রাখা উচিত।',
    'স্থানীয় কর্তৃপক্ষের সরকারি বন্যা সতর্কতা চিহ্নগুলো চিনতে শিখতে হবে।',
    'বন্যা আসার আগে মূল্যবান জিনিস ও বৈদ্যুতিক যন্ত্রপাতি উঁচু তাকে সরিয়ে রাখতে হবে।',
    'বন্যার আশঙ্কা থাকলে মূল সুইচ থেকে বিদ্যুৎ ও গ্যাস বন্ধ করে দিতে হবে।',
    'বন্যার পানি অগভীর ও শান্ত মনে হলেও তার মধ্য দিয়ে হাঁটা উচিত নয়।',
    'মাত্র ছয় ইঞ্চি দ্রুতগতির পানি একজন মানুষকে ফেলে দিতে পারে।',
    'বন্যা কবলিত রাস্তায় গাড়ি চালানো উচিত নয় — ফিরে যাও, ডুববে না।',
    'এক ফুট দ্রুতগতির পানিই একটি গাড়িকে ভাসিয়ে নিতে যথেষ্ট।',
    'বন্যা সতর্কতা জারি হওয়া মাত্র উঁচু স্থানে চলে যাওয়া উচিত।',
    'বন্যার পানিতে পয়ঃনিষ্কাশন বা রাসায়নিক দূষণ থাকতে পারে, তাই তা স্পর্শ করা এড়িয়ে চলতে হবে।',
    'বন্যার পানিতে পড়ে থাকা বিদ্যুতের তার থেকে অনেক দূরে থাকতে হবে।',
    'ভারী বৃষ্টির সময় নদীর তীর, খাল ও ড্রেন থেকে দূরে থাকা উচিত।',
    'কোনো ভবনে আটকা পড়লে সবচেয়ে উঁচু তলায় যেতে হবে, তবে বন্ধ চিলেকোঠায় নয়।',
    'বন্ধ চিলেকোঠায় লুকানোর বদলে জানালা বা ছাদ থেকে সাহায্যের সংকেত দেওয়া উচিত।',
    'সরে যাওয়ার নির্দেশের জন্য সবসময় বিশ্বস্ত বড় ও স্থানীয় কর্তৃপক্ষের কথা শুনতে হবে।',
    'বন্যার পরে দূষিত হতে পারে বলে পানের পানি ফুটিয়ে বা পরিশোধন করে নেওয়া উচিত।',
    'বন্যায় ডুবে যাওয়া বৈদ্যুতিক যন্ত্র বড় কেউ পরীক্ষা না করা পর্যন্ত ব্যবহার করা উচিত নয়।',
    'বন্যার পানিতে সাপ ও পোকামাকড় ভেসে আসতে পারে, তাই সতর্ক থাকতে হবে।',
    'বন্যার পরে ফাটল ধরা বা দুর্বল দেখতে ভবন থেকে দূরে থাকা উচিত।',
    'বন্যা কবলিত এলাকার বাইরে পরিবারের জরুরি যোগাযোগ তালিকা ও মিলনস্থল ঠিক রাখতে হবে।',
    'জাতীয় জরুরি সহায়তা নম্বরটি প্রতিটি শিশুর মুখস্থ রাখা উচিত।',
    'পরিবারকে নিয়মিত বন্যা থেকে সরে যাওয়ার পরিকল্পনা অনুশীলন করা উচিত যাতে সবাই করণীয় জানে।',
  ],
  stepIcons: [
    '🗺️', '📻', '🎒', '📄', '⚠️', '📦', '🔌', '🌊',
    '🚶', '💦', '🚗', '⛰️', '🤢', '⚡', '🌧️', '🏠',
    '🪟', '👨‍👩‍👧', '💧', '🔧', '🐍', '🏚️', '📞', '☎️', '🔁',
  ],
);

final Quiz floodQuiz = const Quiz(
  id: 'q2',
  moduleId: 'm2',
  title: 'Flood Safety Quiz',
  difficulty: 'Easy',
  questions: [
    QuizQuestion(
      question: 'Where should you go during a flood warning?',
      questionBn: 'বন্যার সতর্কতার সময় তোমার কোথায় যাওয়া উচিত?',
      options: ['Higher ground', 'Basement', 'Riverside', 'Stay outside'],
      optionsBn: ['উঁচু জায়গায়', 'বেসমেন্টে', 'নদীর ধারে', 'বাইরে থাকো'],
      correctIndex: 0,
    ),
    QuizQuestion(
      question: 'Is it safe to walk through moving flood water?',
      questionBn: 'দ্রুতগতির বন্যার পানির মধ্য দিয়ে হাঁটা কি নিরাপদ?',
      options: ['Yes, always', 'No, never', 'Only if shallow', 'Only with shoes'],
      optionsBn: ['হ্যাঁ, সবসময়', 'না, কখনোই না', 'শুধু অগভীর হলে', 'শুধু জুতা পরলে'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What should you do if you see a flooded road while driving?',
      questionBn: 'গাড়ি চালানোর সময় বন্যা কবলিত রাস্তা দেখলে তোমার কী করা উচিত?',
      options: ['Drive through fast', 'Turn around', 'Drive slowly through', 'Stop and wait inside'],
      optionsBn: ['দ্রুত পার হও', 'ফিরে যাও', 'ধীরে ধীরে পার হও', 'থেমে ভেতরে অপেক্ষা করো'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What should you do with electricity and gas before a flood?',
      questionBn: 'বন্যার আগে বিদ্যুৎ ও গ্যাসের ক্ষেত্রে তোমার কী করা উচিত?',
      options: ['Leave them on', 'Turn them off at the main switch', 'Ignore them', 'Use more appliances'],
      optionsBn: ['চালু রাখা', 'মূল সুইচ থেকে বন্ধ করা', 'উপেক্ষা করা', 'বেশি যন্ত্র ব্যবহার করা'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Why should you avoid touching flood water?',
      questionBn: 'বন্যার পানি স্পর্শ করা এড়ানো উচিত কেন?',
      options: [
        'It might be contaminated',
        'It is too cold',
        'It stains clothes',
        'It has no reason',
      ],
      optionsBn: [
        'এতে দূষণ থাকতে পারে',
        'এটা খুব ঠান্ডা',
        'এতে কাপড় দাগ পড়ে',
        'কোনো কারণ নেই',
      ],
      correctIndex: 0,
    ),
    QuizQuestion(
      question: 'If trapped in a building during a flood, where should you go?',
      questionBn: 'বন্যার সময় কোনো ভবনে আটকা পড়লে তোমার কোথায় যাওয়া উচিত?',
      options: ['Basement', 'Highest level, not a closed attic', 'Ground floor', 'Outside in the water'],
      optionsBn: ['বেসমেন্ট', 'সবচেয়ে উঁচু তলা, বন্ধ চিলেকোঠা নয়', 'নিচতলা', 'পানিতে বাইরে'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Should you drink flood-affected water without treating it?',
      questionBn: 'বন্যা-প্রভাবিত পানি বিশুদ্ধ না করে পান করা উচিত কি?',
      options: ['Yes', 'No, boil or purify it first', 'Only if clear', 'Only a little'],
      optionsBn: ['হ্যাঁ', 'না, আগে ফুটিয়ে বা পরিশোধন করতে হবে', 'শুধু পরিষ্কার হলে', 'শুধু অল্প'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What might be hiding in flood water that you should watch for?',
      questionBn: 'বন্যার পানিতে কী থাকতে পারে যা নিয়ে সতর্ক থাকা উচিত?',
      options: ['Snakes and insects', 'Toys', 'Flowers', 'Nothing'],
      optionsBn: ['সাপ ও পোকামাকড়', 'খেলনা', 'ফুল', 'কিছুই না'],
      correctIndex: 0,
    ),
    QuizQuestion(
      question: 'What should every family have ready outside the flood zone?',
      questionBn: 'প্রতিটি পরিবারের বন্যা কবলিত এলাকার বাইরে কী প্রস্তুত রাখা উচিত?',
      options: ['Nothing special', 'A meeting point and contact list', 'More furniture', 'A bigger house'],
      optionsBn: ['বিশেষ কিছু না', 'একটি মিলনস্থল ও যোগাযোগ তালিকা', 'আরো আসবাবপত্র', 'বড় বাড়ি'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'How much moving water can sweep away a car?',
      questionBn: 'কতটুকু দ্রুতগতির পানি একটি গাড়িকে ভাসিয়ে নিতে পারে?',
      options: ['One foot', 'Ten feet', 'It never happens', 'Only a flood wave'],
      optionsBn: ['এক ফুট', 'দশ ফুট', 'এটা কখনো হয় না', 'শুধু বন্যার ঢেউ'],
      correctIndex: 0,
    ),
  ],
);
