import '../models/models.dart';

final LessonModule strangerModule = const LessonModule(
  id: 'm4',
  title: 'Stranger Danger',
  titleBn: 'অপরিচিত ব্যক্তি থেকে সাবধানতা',
  category: HazardCategory.stranger,
  summary: 'Learn safe rules for talking to people you don\'t know.',
  summaryBn: 'অপরিচিত মানুষের সাথে কথা বলার নিরাপদ নিয়ম শিখুন।',
  steps: [
    'Never go anywhere with someone you don\'t know, even if they seem nice.',
    'If a stranger offers you candy or gifts, say no and walk away.',
    'Always tell a trusted adult where you are going and who you are with.',
    'Learn your full name, address, and a parent\'s phone number by heart.',
    'If someone makes you feel uncomfortable, trust your feelings and leave.',
    'Never share personal information like your address online with strangers.',
    'Use the buddy system — always try to stay with a friend in public places.',
    'If lost in a public place, look for a police officer or store employee for help.',
    'Never get into a stranger\'s car, even if they say your parent sent them.',
    'Agree on a family password that only trusted people would know.',
    'If a stranger asks for help finding a lost pet, do not go with them — get an adult.',
    'It is okay to say "no" to an adult if something feels wrong.',
    'Shout loudly and run away if a stranger tries to grab you.',
    'Tell a trusted adult immediately if a stranger approaches you in a worrying way.',
    'Be cautious of strangers who try too hard to be your friend very quickly.',
    'Never open the door to strangers when you are home alone.',
    'Remember that most strangers are safe, but always stay careful and alert.',
    'If someone follows you, go to a safe, populated place immediately.',
    'Memorize emergency numbers to call if you ever feel unsafe.',
    'Never post personal details or your location on social media.',
    'If separated from your family in a crowd, stay calm and find a safe adult.',
    'Trust adults like teachers, police officers, or store workers to help you.',
    'Practice saying "no" firmly and confidently in uncomfortable situations.',
    'Always check with a parent before accepting rides or gifts from anyone.',
    'Remember: your safety always matters more than being polite to a stranger.',
  ],
  stepsBn: [
    'অপরিচিত কেউ যতই ভালো মনে হোক, তার সাথে কোথাও যাওয়া উচিত নয়।',
    'কোনো অপরিচিত ব্যক্তি মিষ্টি বা উপহার দিলে না বলে সরে যেতে হবে।',
    'তুমি কোথায় যাচ্ছ ও কার সাথে আছো তা সবসময় বিশ্বস্ত বড়দের জানানো উচিত।',
    'নিজের পুরো নাম, ঠিকানা ও বাবা-মায়ের ফোন নম্বর মুখস্থ রাখা উচিত।',
    'কারো কারণে অস্বস্তি লাগলে নিজের অনুভূতিকে বিশ্বাস করে সেখান থেকে চলে যাওয়া উচিত।',
    'অনলাইনে অপরিচিত মানুষের সাথে নিজের ঠিকানার মতো ব্যক্তিগত তথ্য শেয়ার করা উচিত নয়।',
    'পাবলিক জায়গায় সবসময় বন্ধুর সাথে থাকার চেষ্টা করা উচিত।',
    'কোনো জনবহুল জায়গায় হারিয়ে গেলে সাহায্যের জন্য পুলিশ বা দোকানের কর্মীকে খুঁজতে হবে।',
    'অপরিচিত কেউ বাবা-মা পাঠিয়েছে বললেও তার গাড়িতে ওঠা উচিত নয়।',
    'পরিবারে এমন একটি গোপন শব্দ ঠিক করে রাখা উচিত যা শুধু বিশ্বস্ত মানুষ জানবে।',
    'কোনো অপরিচিত ব্যক্তি হারানো পোষা প্রাণী খুঁজতে সাহায্য চাইলে তার সাথে না গিয়ে বড়দের জানাতে হবে।',
    'কোনো কিছু ভুল মনে হলে বড়দেরও "না" বলা ঠিক আছে।',
    'কেউ ধরার চেষ্টা করলে জোরে চিৎকার করে দৌড়ে পালাতে হবে।',
    'অপরিচিত কেউ চিন্তাজনকভাবে কাছে এলে সাথে সাথে বিশ্বস্ত বড়দের জানাতে হবে।',
    'যারা খুব দ্রুত বন্ধু হতে চায় এমন অপরিচিত মানুষ সম্পর্কে সতর্ক থাকা উচিত।',
    'একা বাসায় থাকলে অপরিচিত কারো জন্য দরজা খোলা উচিত নয়।',
    'বেশিরভাগ অপরিচিত মানুষ নিরাপদ হলেও সবসময় সতর্ক ও সজাগ থাকা উচিত।',
    'কেউ পিছু নিলে সাথে সাথে একটি নিরাপদ, জনবহুল জায়গায় চলে যেতে হবে।',
    'অনিরাপদ মনে হলে কল করার জন্য জরুরি নম্বরগুলো মুখস্থ রাখা উচিত।',
    'সামাজিক যোগাযোগমাধ্যমে ব্যক্তিগত তথ্য বা অবস্থান পোস্ট করা উচিত নয়।',
    'ভিড়ের মধ্যে পরিবার থেকে আলাদা হয়ে গেলে শান্ত থেকে নিরাপদ কোনো বড়কে খুঁজতে হবে।',
    'শিক্ষক, পুলিশ বা দোকানের কর্মীর মতো বড়দের সাহায্যের জন্য বিশ্বাস করা যায়।',
    'অস্বস্তিকর পরিস্থিতিতে দৃঢ়ভাবে ও আত্মবিশ্বাসের সাথে "না" বলার অনুশীলন করা উচিত।',
    'কারো কাছ থেকে লিফট বা উপহার নেওয়ার আগে সবসময় বাবা-মায়ের সাথে যাচাই করা উচিত।',
    'মনে রাখতে হবে: নিজের নিরাপত্তা সবসময় ভদ্রতার চেয়ে বেশি গুরুত্বপূর্ণ।',
  ],
  stepIcons: [
    '🚶', '🍬', '👨‍👩‍👧', '📛', '💭', '🔒', '👬', '👮',
    '🚗', '🔑', '🐶', '🙅', '📢', '🗣️', '🤝', '🚪',
    '😊', '🏃', '📞', '📵', '👪', '👩‍🏫', '💪', '🎁', '❤️',
  ],
);

final Quiz strangerQuiz = const Quiz(
  id: 'q4',
  moduleId: 'm4',
  title: 'Stranger Danger Quiz',
  difficulty: 'Easy',
  questions: [
    QuizQuestion(
      question: 'A stranger offers you candy to go with them. What do you do?',
      questionBn: 'একজন অপরিচিত ব্যক্তি তোমাকে মিষ্টি দিয়ে সাথে যেতে বলে। তুমি কী করবে?',
      options: [
        'Go with them',
        'Say no and tell a trusted adult',
        'Take the candy quietly',
        'Ignore and walk away alone',
      ],
      optionsBn: [
        'তাদের সাথে যাবে',
        'না বলবে এবং বিশ্বস্ত বড়দের জানাবে',
        'চুপচাপ মিষ্টি নেবে',
        'উপেক্ষা করে একা চলে যাবে',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Should you get into a stranger\'s car if they say your parent sent them?',
      questionBn: 'বাবা-মা পাঠিয়েছে বললেও অপরিচিত ব্যক্তির গাড়িতে ওঠা উচিত কি?',
      options: ['Yes, always', 'No, never', 'Only if they know your name', 'Only during the day'],
      optionsBn: ['হ্যাঁ, সবসময়', 'না, কখনোই না', 'শুধু নাম জানলে', 'শুধু দিনের বেলায়'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What should you memorize in case you get lost?',
      questionBn: 'হারিয়ে গেলে কী মুখস্থ রাখা উচিত?',
      options: [
        'Your favorite color',
        'Your name, address, and a parent\'s phone number',
        'A cartoon character',
        'Nothing is needed',
      ],
      optionsBn: [
        'প্রিয় রং',
        'নাম, ঠিকানা ও বাবা-মায়ের ফোন নম্বর',
        'একটি কার্টুন চরিত্র',
        'কিছুই দরকার নেই',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'If lost in a public place, who should you look for?',
      questionBn: 'জনবহুল জায়গায় হারিয়ে গেলে তোমার কাকে খোঁজা উচিত?',
      options: ['Any stranger', 'A police officer or store employee', 'No one', 'A random car'],
      optionsBn: ['যেকোনো অপরিচিত ব্যক্তি', 'পুলিশ বা দোকানের কর্মী', 'কাউকে না', 'যেকোনো গাড়ি'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What is a family password used for?',
      questionBn: 'পারিবারিক গোপন শব্দ কী কাজে ব্যবহার হয়?',
      options: [
        'To unlock a phone',
        'To confirm someone was really sent by your family',
        'To play a game',
        'It has no use',
      ],
      optionsBn: [
        'ফোন আনলক করতে',
        'কাউকে সত্যিই পরিবার পাঠিয়েছে কিনা নিশ্চিত করতে',
        'খেলার জন্য',
        'কোনো কাজ নেই',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Is it okay to say "no" to an adult if something feels wrong?',
      questionBn: 'কিছু ভুল মনে হলে বড়দের "না" বলা কি ঠিক?',
      options: ['No, never', 'Yes, it is okay', 'Only to strangers', 'Only when alone'],
      optionsBn: ['না, কখনোই না', 'হ্যাঁ, এটা ঠিক আছে', 'শুধু অপরিচিতদের', 'শুধু একা থাকলে'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What should you do if a stranger tries to grab you?',
      questionBn: 'কোনো অপরিচিত ব্যক্তি তোমাকে ধরার চেষ্টা করলে তোমার কী করা উচিত?',
      options: ['Stay quiet', 'Shout loudly and run away', 'Go with them calmly', 'Freeze in place'],
      optionsBn: ['চুপ থাকা', 'জোরে চিৎকার করে দৌড়ানো', 'শান্তভাবে তার সাথে যাওয়া', 'জায়গায় জমে থাকা'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Should you open the door to a stranger when home alone?',
      questionBn: 'একা বাসায় থাকলে অপরিচিত কারো জন্য দরজা খোলা উচিত কি?',
      options: ['Yes, always', 'No', 'Only if they knock softly', 'Only during the day'],
      optionsBn: ['হ্যাঁ, সবসময়', 'না', 'শুধু আস্তে নক করলে', 'শুধু দিনের বেলায়'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Is it safe to post your location on social media?',
      questionBn: 'সামাজিক যোগাযোগমাধ্যমে অবস্থান পোস্ট করা কি নিরাপদ?',
      options: ['Yes, always', 'No, it is not safe', 'Only on weekends', 'Only for friends'],
      optionsBn: ['হ্যাঁ, সবসময়', 'না, এটা নিরাপদ নয়', 'শুধু সপ্তাহান্তে', 'শুধু বন্ধুদের জন্য'],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'If separated from family in a crowd, what should you do?',
      questionBn: 'ভিড়ের মধ্যে পরিবার থেকে আলাদা হয়ে গেলে তোমার কী করা উচিত?',
      options: [
        'Panic and run anywhere',
        'Stay calm and find a safe adult',
        'Hide and wait silently',
        'Follow any nearby stranger',
      ],
      optionsBn: [
        'ঘাবড়ে গিয়ে যেকোনো দিকে দৌড়ানো',
        'শান্ত থেকে নিরাপদ বড়কে খোঁজা',
        'লুকিয়ে চুপচাপ অপেক্ষা করা',
        'কাছের যেকোনো অপরিচিত ব্যক্তিকে অনুসরণ করা',
      ],
      correctIndex: 1,
    ),
  ],
);
