import '../models/models.dart';

final LessonModule strangerModule = const LessonModule(
  id: 'm4',
  title: 'Stranger Danger',
  titleBn: 'অপরিচিত ব্যক্তি থেকে সাবধানতা',
  category: HazardCategory.stranger,
  summary: 'Learn safe rules for talking to people you don\'t know.',
  summaryBn: 'অপরিচিত মানুষের সাথে কথা বলার নিরাপদ নিয়ম শিখুন।',
  steps: [
    'Never go anywhere with a stranger, even if they seem nice or offer help.',
    'Never accept candy, gifts, or toys from someone you don\'t know.',
    'Never get into a stranger\'s car, even if they say your parents sent them.',
    'Remember the rule: say No, Go away, and Tell a trusted adult.',
    'Know who your trusted adults are, like parents, teachers, and family members.',
    'If someone tries to grab you, yell loudly and run toward a safe place.',
    'Memorize your parents\' phone number and home address.',
    'Never share your name, school, or address with strangers online.',
    'If you get lost, look for a police officer or uniformed staff member, not just any stranger.',
    'Always use the buddy system and never wander off alone.',
    'Set up a secret family password so you know if someone is really sent by your parents.',
    'Never open the door for a stranger when you are home alone.',
    'Trust your feelings — if something feels wrong, walk away immediately.',
    'Never tell a stranger that you are home alone.',
    'Keep at least an arm\'s length of distance from strangers.',
    'If grabbed, shout "This is not my parent!" so others notice.',
    'Always tell a trusted adult about any stranger encounter, even if nothing bad happened.',
    'Avoid walking alone in isolated areas, empty streets, or parks.',
    'Never help a stranger look for a lost pet or item, especially in a private place.',
    'Be careful of strangers in a car asking you for directions.',
    'If someone follows you, go to a shop or crowded place and tell an adult right away.',
    'Practice stranger danger safety drills at home with your family.',
    'After any incident, describe the stranger\'s appearance clearly to a trusted adult or police.',
  ],
  stepsBn: [
    'অপরিচিত ব্যক্তি যত ভালোই মনে হোক বা সাহায্যের কথা বলুক, তার সাথে কখনো কোথাও যেও না।',
    'অপরিচিত কারো কাছ থেকে মিষ্টি, উপহার বা খেলনা কখনো নেবে না।',
    'অপরিচিত কারো গাড়িতে কখনো উঠবে না, এমনকি তারা যদি বলে যে তোমার বাবা-মা পাঠিয়েছে।',
    'মনে রাখো নিয়ম: না বলো, দূরে সরে যাও, এবং বিশ্বস্ত বড়দের জানাও।',
    'তোমার বিশ্বস্ত বড়রা কারা তা জেনে রাখো, যেমন বাবা-মা, শিক্ষক ও পরিবারের সদস্যরা।',
    'কেউ তোমাকে ধরার চেষ্টা করলে জোরে চিৎকার করো এবং নিরাপদ জায়গার দিকে দৌড়াও।',
    'তোমার বাবা-মায়ের ফোন নম্বর ও বাসার ঠিকানা মুখস্থ রাখো।',
    'অনলাইনে অপরিচিত কারো সাথে তোমার নাম, স্কুল বা ঠিকানা শেয়ার কোরো না।',
    'হারিয়ে গেলে পুলিশ বা ইউনিফর্ম পরা কর্মীর কাছে যাও, যেকোনো অপরিচিত মানুষের কাছে নয়।',
    'সবসময় সঙ্গী নিয়ে চলো এবং কখনো একা ঘুরে বেড়িও না।',
    'পরিবারে একটি গোপন পাসওয়ার্ড ঠিক করে রাখো, যাতে বুঝতে পারো কেউ সত্যিই তোমার বাবা-মায়ের পাঠানো কিনা।',
    'একা বাসায় থাকলে অপরিচিত কারো জন্য দরজা কখনো খুলো না।',
    'নিজের অনুভূতিকে বিশ্বাস করো — কিছু ভুল মনে হলে সাথে সাথে সরে যাও।',
    'অপরিচিত কাউকে কখনো বোলো না যে তুমি একা বাসায় আছো।',
    'অপরিচিত মানুষের থেকে অন্তত এক হাত দূরত্ব বজায় রাখো।',
    'কেউ ধরলে চিৎকার করে বলো "এটা আমার বাবা-মা নয়!" যাতে অন্যরা লক্ষ্য করে।',
    'কোনো খারাপ কিছু না ঘটলেও অপরিচিত মানুষের সাথে যেকোনো ঘটনার কথা বিশ্বস্ত বড়দের জানাও।',
    'নির্জন এলাকা, ফাঁকা রাস্তা বা পার্কে একা হাঁটা এড়িয়ে চলো।',
    'অপরিচিত কাউকে হারানো পোষা প্রাণী বা জিনিস খুঁজতে সাহায্য কোরো না, বিশেষ করে নির্জন জায়গায়।',
    'গাড়িতে থাকা অপরিচিত মানুষ রাস্তা জিজ্ঞেস করলে সতর্ক থাকো।',
    'কেউ তোমাকে অনুসরণ করলে দোকানে বা ভিড়ের জায়গায় গিয়ে সাথে সাথে একজন বড়কে জানাও।',
    'পরিবারের সাথে বাসায় অপরিচিত ব্যক্তি বিষয়ক নিরাপত্তা মহড়া অনুশীলন করো।',
    'কোনো ঘটনার পর অপরিচিত ব্যক্তির চেহারা বিশ্বস্ত বড় বা পুলিশকে স্পষ্টভাবে বর্ণনা করো।',
  ],
  stepIcons: [
    '🙅', '🍬', '🚗', '✋', '👨‍👩‍👧', '📢', '📱', '💻',
    '👮', '🧑‍🤝‍🧑', '🔑', '🚪', '💭', '🏠', '📏', '😱',
    '🗣️', '🌳', '🐶', '🚙', '🏪', '🎭', '📝',
  ],
);

final Quiz strangerQuiz = const Quiz(
  id: 'q4',
  moduleId: 'm4',
  title: 'Stranger Danger Quiz',
  difficulty: 'Easy',
  questions: [
    QuizQuestion(
      question: 'A stranger offers you candy to go with them. What do you do?',
      questionBn: 'একজন অপরিচিত ব্যক্তি তোমাকে মিষ্টি দিয়ে সাথে যেতে বলে। তুমি কী করবে?',
      options: [
        'Go with them',
        'Say no and tell a trusted adult',
        'Take the candy quietly',
        'Ignore and walk away alone',
      ],
      optionsBn: [
        'তাদের সাথে যাবে',
        'না বলবে এবং বিশ্বস্ত বড়দের জানাবে',
        'চুপচাপ মিষ্টি নেবে',
        'উপেক্ষা করে একা চলে যাবে',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What should you do if a stranger asks you to get in their car?',
      questionBn: 'একজন অপরিচিত ব্যক্তি তোমাকে তার গাড়িতে উঠতে বললে তুমি কী করবে?',
      options: [
        'Get in quickly',
        'Say no and run to a trusted adult',
        'Ask where they are going first',
        'Go if they say it is an emergency',
      ],
      optionsBn: [
        'দ্রুত উঠে পড়বে',
        'না বলবে এবং বিশ্বস্ত বড়দের কাছে দৌড়াবে',
        'আগে জিজ্ঞেস করবে তারা কোথায় যাচ্ছে',
        'জরুরি বললে যাবে',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'If you get lost in a mall, who should you look for?',
      questionBn: 'শপিং মলে হারিয়ে গেলে তোমার কার কাছে যাওয়া উচিত?',
      options: [
        'Any stranger nearby',
        'A police officer or uniformed staff member',
        'Someone who looks kind',
        'Wait alone until someone finds you',
      ],
      optionsBn: [
        'কাছাকাছি যেকোনো অপরিচিত ব্যক্তি',
        'পুলিশ বা ইউনিফর্ম পরা কর্মী',
        'দেখতে ভালো মানুষ মনে হয় এমন কেউ',
        'একা অপেক্ষা করা যতক্ষণ না কেউ খুঁজে পায়',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What is a family safe word used for?',
      questionBn: 'পরিবারের গোপন পাসওয়ার্ড কী কাজে ব্যবহার হয়?',
      options: [
        'To play a game',
        'To confirm someone was really sent by your parents',
        'To share with everyone you meet',
        'To use as a nickname',
      ],
      optionsBn: [
        'খেলার জন্য',
        'কেউ সত্যিই বাবা-মায়ের পাঠানো কিনা তা নিশ্চিত করতে',
        'সবার সাথে শেয়ার করার জন্য',
        'ডাকনাম হিসেবে ব্যবহার করতে',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'If someone tries to grab you, what should you do?',
      questionBn: 'কেউ তোমাকে ধরার চেষ্টা করলে তোমার কী করা উচিত?',
      options: [
        'Stay quiet',
        'Yell loudly and run to a safe place',
        'Follow them calmly',
        'Cry silently',
      ],
      optionsBn: [
        'চুপ থাকা',
        'জোরে চিৎকার করে নিরাপদ জায়গায় দৌড়ানো',
        'শান্তভাবে তাদের অনুসরণ করা',
        'চুপচাপ কাঁদা',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'Should you open the door for a stranger when you are home alone?',
      questionBn: 'একা বাসায় থাকলে অপরিচিত কারো জন্য দরজা খোলা উচিত কি?',
      options: [
        'Yes, always',
        'No, never',
        'Only if they seem friendly',
        'Only if they knock twice',
      ],
      optionsBn: [
        'হ্যাঁ, সবসময়',
        'না, কখনোই না',
        'শুধু বন্ধুত্বপূর্ণ মনে হলে',
        'শুধু দুইবার নক করলে',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'What should you do if a stranger in a car asks you for directions?',
      questionBn: 'গাড়িতে থাকা অপরিচিত ব্যক্তি রাস্তা জিজ্ঞেস করলে তোমার কী করা উচিত?',
      options: [
        'Get close to help them',
        'Stay at a safe distance and be cautious',
        'Get in the car to show them',
        'Ignore your own safety and help',
      ],
      optionsBn: [
        'কাছে গিয়ে সাহায্য করা',
        'নিরাপদ দূরত্বে থেকে সতর্ক থাকা',
        'দেখাতে গাড়িতে ওঠা',
        'নিজের নিরাপত্তা উপেক্ষা করে সাহায্য করা',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'If you feel uncomfortable around someone, even without a clear reason, what should you do?',
      questionBn: 'কোনো কারণ ছাড়াই কারো আশেপাশে অস্বস্তি বোধ করলে তোমার কী করা উচিত?',
      options: [
        'Ignore the feeling',
        'Trust your feelings and walk away',
        'Wait and see what happens',
        'Stay to be polite',
      ],
      optionsBn: [
        'অনুভূতিটা উপেক্ষা করা',
        'নিজের অনুভূতিকে বিশ্বাস করে সরে যাওয়া',
        'অপেক্ষা করে দেখা কী হয়',
        'ভদ্রতার জন্য থেকে যাওয়া',
      ],
      correctIndex: 1,
    ),
    QuizQuestion(
      question: 'After any encounter with a stranger that felt weird, what should you always do?',
      questionBn: 'অপরিচিত ব্যক্তির সাথে অদ্ভুত লাগা কোনো ঘটনার পর তোমার সবসময় কী করা উচিত?',
      options: [
        'Keep it a secret',
        'Tell a trusted adult right away',
        'Forget about it',
        'Only tell your friends',
      ],
      optionsBn: [
        'গোপন রাখা',
        'সাথে সাথে বিশ্বস্ত বড়দের জানানো',
        'ভুলে যাওয়া',
        'শুধু বন্ধুদের বলা',
      ],
      correctIndex: 1,
    ),
  ],
);
