// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8IhXNwJWjw9OqSU165KcI4v8FVfacBE',
    appId: '1:563787259787:web:f6d68b3e186ab20194998e',
    messagingSenderId: '563787259787',
    projectId: 'safezone-ultra-3a975',
    authDomain: 'safezone-ultra-3a975.firebaseapp.com',
    storageBucket: 'safezone-ultra-3a975.firebasestorage.app',
    measurementId: 'G-9TXSZ6VB4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyxDvFuT6mjCU6VWBpmjn3UMgMFo_fqOk',
    appId: '1:563787259787:android:6d516dfbf6a9145394998e',
    messagingSenderId: '563787259787',
    projectId: 'safezone-ultra-3a975',
    storageBucket: 'safezone-ultra-3a975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCARN67V9dTPiajc-s2rPl3jla_2HP1gqE',
    appId: '1:563787259787:ios:c2cb764c3d949e4694998e',
    messagingSenderId: '563787259787',
    projectId: 'safezone-ultra-3a975',
    storageBucket: 'safezone-ultra-3a975.firebasestorage.app',
    iosBundleId: 'com.mist.safezoneUltra',
  );
}
